### ISSUE TITLE
context manager capabilities for cluster config

### ISSUE THREAD

**Issue by rafaelpierre** [rafaelpierre/pyjaws#10]
## Expected Behavior

Should be possible to do something like: `with Cluster(...) as cluster:` and declare tasks within this `with` block. This would result in the `cluster` object being assigned to all tasks declared within this block.

## Current Behavior

NA

## Your Environment

* pyjaws version used:

**Comment by aaravind100** [comment]
Hey @rafaelpierre, this is for syntactic sugar? We don't seem to access any resources in the cluster.

Adding something like this to Cluster...
```python
class Cluster(BaseModel):
   ...
    def __enter__(self) -> Cluster:
        return self

    def __exit__(self, *args):
        pass
```
We can use it like this...
```python

with Cluster(...) as cluster:
    task_1 = NotebookTask(
    ...
    cluster=cluster)
```

I've seen `with` syntax used quite differently in the kubeflow dsl though, [ExitHandler](https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html#kfp.dsl.ExitHandler) & [ParallelFor](https://kubeflow-pipelines.readthedocs.io/en/stable/source/kfp.dsl.html#kfp.dsl.ParallelFor) for example.

**Comment by rafaelpierre** [comment]
Yes, exactly @aaravind100 - this is more syntactic sugar :)

we should keep both flavors available: 1. assigning clusters to tasks (which basically maps the `cluster_key` to the task payload) and 2. with the context manager - `with Cluster(...) as cluster` as you pointed out

wanna take a stab at it?

**Comment by aaravind100** [comment]
Yep, I can take this. I'll create a pr in sometime.

**Comment by rafaelpierre** [comment]
Amazing @aaravind100!

**Comment by rafaelpierre** [comment]
Closed with https://github.com/rafaelpierre/pyjaws/pull/14
