### ISSUE TITLE
Support for Databricks SDK

### ISSUE THREAD

**Issue by rafaelvp-db** [rafaelpierre/pyjaws#16]
## Expected Behavior

Currently, we use Databricks Jobs and Workflows REST API. We should replace this by Databricks Python SDK. Benefits:

* Not having to adapt to potential changes in the API
* Removing dependency on Databricks CLI (which doesn't have 100% coverage at the moment)
* Removing the complexity associated with Jinja templating, which will help increase the coverage of PyJaws as well

## Current Behavior

PyJaws integrates with Databricks REST API

## Your Environment

* pyjaws version used:

**Comment by rafaelpierre** [comment]
Closed by #30
