### ISSUE TITLE
implicit context managers

### ISSUE THREAD

**Issue by rafaelpierre** [rafaelpierre/pyjaws#22]
## Expected Behavior

Changing the way Cluster context managers work, so that we don't need to assign clusters to tasks inside the `with Cluster(...) as cluster` block

## Your Environment

* pyjaws version used:

**Comment by aaravind100** [comment]
@rafaelpierre there doesn't seem to be a straight forward way of doing this in python. After a bit of googling, I found [this](https://stackoverflow.com/a/74865454) so thread.

Seems like a hacky solution, a downside I see is that it'll cause a race when threads are used to create clusters (maybe not a problem for most use cases). We could get around this with a thread lock.

Do you have a better approach in mind?

**Comment by rafaelpierre** [comment]
Hey @aaravind100! Sorry for the delay

Yeah I gotta be honest, not entirely sure of the best way to achieve this. I was thinking of looking at the implementation currently used by Airflow for doing something similar for DAG declaration. Agree a thread lock could be an interesting solution

I want to take a stab at it in the coming days - if you're interested we can work on this together. WDYT?

**Comment by rafaelpierre** [comment]
Still gotta dig further but guess this is where it starts:

```
# Context Manager -----------------------------------------------
    def __enter__(self):
        DagContext.push_context_managed_dag(self)
        return self

    def __exit__(self, _type, _value, _tb):
        DagContext.pop_context_managed_dag()
```

https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L3786

**Comment by aaravind100** [comment]
hey @rafaelpierre np, I sorta got it working in my local branch, i'll push the branch to my fork when i get back to my machine. You can take a look at it.

**Comment by aaravind100** [comment]
@rafaelpierre can you take a look at this commit [41ce271](https://github.com/aaravind100/pyjaws/commit/41ce2715e4c7d1269ccaeb34df6c2c9f876f402a#diff-61096748e792d7d8f4e19e3deae6830c308ad8ccb26ebb28ee0be1230d00d9a5)

**Comment by rafaelpierre** [comment]
Closed by https://github.com/rafaelpierre/pyjaws/pull/23
